config/routes.rb
Crashfinder::Application.routes.draw do
  get "top_ten/index"

  get "year_stats/index"

  get "trends/index"

  get "home/index"

  root to: 'home#index'
  
  resources :clusters, only: [:index]
  resources :top, only: [:index]
  
  resources :locations
  resources :trends, only: [:index] do
    collection do
      get :yearly
      get :monthly
      get :weekday
    end
  end
  
  match '/auth/:provider/callback', to: 'sessions#create', as: :signin
  match "/signout" => "sessions#destroy", as: :signout

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Crash Finder"
    = csrf_meta_tags
    %script{:src => "https://maps.googleapis.com/maps/api/js?key=#{Rails.configuration.google_maps_api_key}&sensor=false&libraries=drawing", :type => "text/javascript"}
    %script{:src => "https://browserid.org/include.js", :type => "text/javascript"}
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "https://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35143950-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
      
  %body
    - if current_user
      %span{:id => "user-email", :style => "display: none"}
        = current_user.uid
    #spinner{:style => "display: none;"}
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Crash Finder", root_path, class: 'brand'
          .container.nav-collapse
            %ul.nav
              %li= link_to "Top 100", top_index_path
              %li= link_to "Browse", clusters_path
              - if current_user
                %li= link_to "Locations", locations_path
                %li= link_to "Trends", "/trends"
                %li= link_to "Sign out", '#', id: 'signout_button'
              - else
                %li= link_to "Sign in", '#', id: 'signin_button'
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      = yield
      %footer
        %p &copy; Luke Bredeson 2012-2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    :javascript
      $(function() {
        var userEmail = $("#user-email").text().trim();
        if (userEmail === "") {
            userEmail = null;
        }
        navigator.id.watch({
          loggedInUser: userEmail,
          onlogin: function(assertion) {
            $.ajax({
              type: 'POST',
              url: '#{signin_path("browser_id")}',
              data: { assertion: assertion },
              success: function(res, status, xhr) { window.location.reload(); },
              error: function(xhr, status, err) {
                navigator.id.logout();
                alert("Login failure: " + err);
              }
            });
          },
          onlogout: function() {
            $.ajax({
              type: 'POST',
              url: '#{signout_path}',
              success: function(res, status, xhr) { window.location.reload(); },
              error: function(xhr, status, err) { alert("Logout failure: " + err); }
            });
          }
        });
        $('#signin_button').on('click', function(e) {
          e.preventDefault();
          navigator.id.request();
        });
        $('#signout_button').on('click', function(e) {
          e.preventDefault();
          navigator.id.logout();
        });
      });
    = yield :javascript